module.exports = {
  presetPackages: [
    ['browserify', 'webpack', 'rollup', 'parcel-bundler'],
    ['recompose', 'mobx'],
    [
      'glamor',
      'aphrodite',
      'radium',
      'glamorous',
      'styled-components',
      'jss',
      'emotion',
    ],
    // ['lodash', 'underscore'],
    ['node-sass', 'less', 'stylus'],
    // ['gulp', 'grunt'],
    ['react', 'angular', '@angular/core', 'ember-cli', 'vue'],
    ['log4js', 'winston'],
    // ['meteor-node-stubs', 'sails'],
  ],
  palette: [
    '#2196F3',
    '#f44336',
    '#FF9800',
    '#BBCC24',
    '#9C27B0',
    '#795548',
    '#3F51B5',
    '#9E9E9E',
    '#FFEB3B',
    '#c0392b',
    '#22aa99',
    '#109618',
    '#651067',
    '#dd4477',
    '#5574a6',
  ],
};
